### ISSUE TITLE
Change the fonts and alignment in membership page

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#12]
Hello

Change the alignment and fonts in for below membership page

http://www.o2spa.org/membership/

Regards

Prasad

![2](https://cloud.githubusercontent.com/assets/16165106/13196024/b8cc4222-d7e8-11e5-8b26-84b8d009e263.jpg)
![1](https://cloud.githubusercontent.com/assets/16165106/13196022/b8cb5db2-d7e8-11e5-8d6e-bc7a8d7aeeab.jpg)
![5](https://cloud.githubusercontent.com/assets/16165106/13196026/b8ce51b6-d7e8-11e5-9f55-4aa4d07f084f.jpg)
![4](https://cloud.githubusercontent.com/assets/16165106/13196023/b8cc323c-d7e8-11e5-939c-0ab4b45d272f.jpg)
![3](https://cloud.githubusercontent.com/assets/16165106/13196025/b8cdbf62-d7e8-11e5-9a4d-424de27502aa.jpg)

**Comment by arish-ddeveloper** [comment]
Done.
