### ISSUE TITLE
Create a new outlet in Hyderabad location

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#13]
Hello Arish,

Create new outlet in hyderabad. Attached doucment consists the outlet description, address and map link
[vivanta.docx](https://github.com/adnan1111/o2spaorg/files/139075/vivanta.docx)
![vivanta](https://cloud.githubusercontent.com/assets/16165106/13196114/9012504e-d7eb-11e5-9301-89e9fbdbb95b.png)

**Comment by arish-ddeveloper** [comment]
Done.
