### ISSUE TITLE
Create a new outlet in Jaipur

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#14]
Hello Arish,

Create new outlet in Jaipur. Attached doucment consists the outlet description, address, map link and also menu and image are attached

Regards
Prasad

[Jaipur Tulip.docx](https://github.com/adnan1111/o2spaorg/files/139081/Jaipur.Tulip.docx)
[Jaipur Tulip.pdf](https://github.com/adnan1111/o2spaorg/files/139083/Jaipur.Tulip.pdf)
![tulip jaipur](https://cloud.githubusercontent.com/assets/16165106/13196213/12540c9e-d7ee-11e5-9705-16bf0166fad1.png)

**Comment by arish-ddeveloper** [comment]
Done.
