### ISSUE TITLE
Create a new outlet in Mumbai location

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#17]
Hello
Attached document consists the new outlet description, address and maplink and also attached out
[
Mumbai Niranta.docx](https://github.com/adnan1111/o2spaorg/files/139091/Mumbai.Niranta.docx)
![niranta](https://cloud.githubusercontent.com/assets/16165106/13196316/a9921a7c-d7f0-11e5-9f7e-18117c055649.png)

let image

**Comment by arish-ddeveloper** [comment]
Done.
