### ISSUE TITLE
Website Issues need to fix immediately

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#31]
Hello Arish

Attached document consists the issues on the website which are recommended by SEO outsourcing company. Please work and fix the issue as soon as possible

[Changes on the website - Copy.docx](https://github.com/adnan1111/o2spaorg/files/167193/Changes.on.the.website.-.Copy.docx)

Regards

Prasad

**Comment by arish-ddeveloper** [comment]
Country dropdown issue fixed.

Request the SEO company to give task in detail about mobile site issue. A professional company could not give such poorly researched issues without any fact.

They are unprofessional that the country drop down menu can be updated from the wp admin but they want the ftp for this.

I'm kindly requesting you not to give them any access to the site as they are sure to breakdown the site with such a complex development that I did to satisfy your boss. Hope you understand.

Thanks & Regards
Arish

**Comment by adnan1111** [comment]
Hello Arish,

We already informed them that the technical part will take care by the website developer. Regarding the mobile issues we update you in detail.
