### ISSUE TITLE
Kolkata Park Plaza missing in Dropdown

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#33]
Hi Arish
Please add kolkata parkplaza in dropdown and also also on uae website.

Note: The picture is attached for clear idea

Regards
![kolkata](https://cloud.githubusercontent.com/assets/16165106/13746205/515cfc02-ea18-11e5-8e96-8627304a1207.jpg)

Prasad

**Comment by arish-ddeveloper** [comment]
Done.
