### ISSUE TITLE
Create a new outlet in uae.o2spa.org

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#37]
Hello Arish,
Create a new outlet in uae.o2spa.org wesite. Attached is the document ,image and menu.
[Millennium Hotel Fujairah.docx](https://github.com/adnan1111/o2spaorg/files/200817/Millennium.Hotel.Fujairah.docx)
[Millennium Hotel Fujairah Main menu .pdf](https://github.com/adnan1111/o2spaorg/files/200830/Millennium.Hotel.Fujairah.Main.menu.pdf)
![fujairah millennium](https://cloud.githubusercontent.com/assets/16165106/14226474/ec95fa88-f900-11e5-988f-b124900bd594.png)

Note: Also create the outlet in o2spa.org and also in drop down enquiry forms

**Comment by arish-ddeveloper** [comment]
Done.
