### ISSUE TITLE
Upload menu for Kolkata Park Plaza

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#38]
Hello Arish,

Uplaod a menu at  below page
[Kolkata Park Plaza.pdf](https://github.com/adnan1111/o2spaorg/files/200835/Kolkata.Park.Plaza.pdf)

http://www.o2spa.org/locations/india/spa-in-kolkata/kolkata-park-plaza/

**Comment by arish-ddeveloper** [comment]
Done.
