### ISSUE TITLE
Upload an image in News & Important Announcement

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#39]
Hello Arish,

Uplaod attached image in news and important announcement in uae.o2spa.org website 
![o2 spa in uae](https://cloud.githubusercontent.com/assets/16165106/14226697/20fe373a-f907-11e5-8ada-0ea8e5a8a7e3.jpg)

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Done.
