### ISSUE TITLE
New outlet in uae.o2spa.org.

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#43]
Hello Arish,,

Add the new outlet in uae.o2spa.org. Attached word document  and png image

Note: Add new outlet in o2spa.org and in feedback form of uae.o2spa.org

[new outlet uae.docx](https://github.com/adnan1111/o2spaorg/files/227971/new.outlet.uae.docx)
![uae new outlet](https://cloud.githubusercontent.com/assets/16165106/14675916/da94263a-0728-11e6-948a-ef9058509be5.png)

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Added. Also feedback and book now dropdown have been updated.
