### ISSUE TITLE
Change the picture for Taj ViVanta

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#44]
Hello Arish

Change the picture of Taj Vivanta Hotel at url http://www.o2spa.org/locations/india/spa-in-hyderabad/

Upload the attached picture

![o2 spa taj vivanta](https://cloud.githubusercontent.com/assets/16165106/14676796/aa53f41a-072c-11e6-98e3-57bcd38d6372.png)

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Done.
