### ISSUE TITLE
New outlet on uae.o2spa.org for Dubai Location

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#50]
Hello Arish 
Create  new outlet for uae.o2spa.org website. Attached document consists the outlet information and  picture
[uae new outlet dubai.docx](https://github.com/adnan1111/o2spaorg/files/245149/uae.new.outlet.dubai.docx)

Note: Create the outlet on o2spa.org website and in feedback form also

![dubai](https://cloud.githubusercontent.com/assets/16165106/14955556/5c30849a-1098-11e6-8646-59bca3026bf4.png)

**Comment by adnan1111** [comment]
Create the outlet with below url on Uae.o2spa.org

http://uae.o2spa.org/locations/uae/dubai/Copthrone-Hotel-Dubai-coming-soon/

**Comment by arish-ddeveloper** [comment]
done.
