### ISSUE TITLE
Place new content in membership page

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#51]
Hello Arish,

Upload new content for the below membership page. The Content is attached

http://www.o2spa.org/membership/.

Place hyper links for memberships at buy now option.

Hyperlink for Premium Memberships 175000 =  http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=579f1035-5714-40d8-9238-40b2aaa641f9
[membership page on website.docx](https://github.com/adnan1111/o2spaorg/files/248280/membership.page.on.website.docx)

Hyperlink for Premium Memberships 125000 = http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=c3d94e12-bd1f-4108-80eb-8c02196f35e0

Hyperlink for Premium Memberships 65000 = "http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=74559ea3-d601-4d3c-a2c0-8d61ea65073f"

Hyperlink for Premium Memberships 25000= "http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=5da85c93-eb39-494a-8ad2-b899f391eab9"

Hyperlink for Premium Memberships 15000="http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=f8e03630-2c89-43ac-96fa-3dc3bf7e79d1"

For Happy Hour Membership the links will be sent in next mail.
[membership page on website.docx](https://github.com/adnan1111/o2spaorg/files/248283/membership.page.on.website.docx)

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Done.

http://www.o2spa.org/membership/
