### ISSUE TITLE
Links for Happy Hours

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#52]
Happy Hour Membership Rs 20,000

http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=8fb52b3e-a663-4b24-8078-ce1dc52dce39

Happy Hour Membership Rs 30,000

http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=336dea22-b2b9-47f4-9b47-fdbe0c0a83f0

Happy Hour Membership 50,000

http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=18be6910-2fcd-4a7f-b535-7ce00396869f

Happy Hour Membership 1,00000

http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=d0320d5b-6efc-4b72-a047-456862d4c6f7

Happy Hour Membership 1,50,0000

http://o2spa.managemyspa.com/webstore/ItemDetails.aspx?webstoretype=0&ItemType=3&ItemId=58b9c4a3-0539-4b58-a03c-7ec45d11c019

**Comment by arish-ddeveloper** [comment]
Done
