### ISSUE TITLE
Membership page table and characterstics

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#53]
Hello Arish,

The table in the membership page should be like attached image same with characteristics

Regards
Prasad
![happy hour table](https://cloud.githubusercontent.com/assets/16165106/15064622/f3946242-1373-11e6-8697-5edcff5acacc.jpg)
![characterstics](https://cloud.githubusercontent.com/assets/16165106/15064626/f7426236-1373-11e6-87c6-5c96fb2d164b.jpg)

**Comment by arish-ddeveloper** [comment]
Done.

**Comment by arish-ddeveloper** [comment]
Done.

**Comment by adnan1111** [comment]
Hello Arish,

The below terms and conditions need to be without spacing
It is "happy hour membership" not "happy hour"
It is "Premium Membership" not "Premium Memberships"

Regards,
Adnan.

On Wed, May 11, 2016 at 11:49 AM, arish-ddeveloper <notifications@github.com

> wrote:
> 
> Done.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/adnan1111/o2spaorg/issues/53#issuecomment-218371927

## 

Syed Adnan Pervez (Adnan),
Digital Marketing Head,
O2 Spa,
Masti Health and Beauty Pvt Ltd
8-2-293/82, P-564/A-31 Co-operative Hs Building Society Road-92,
Jubilee Hills, MLA Colony,
Banjara Hills, Hyderabad, Telangana
mailto:adnan@o2spa. adnan@o2spa.orgin , mktg@o2spa.org
Mobile No.+91 9573057578/+91 9030089098| www.o2spa.org
facebook https://www.facebook.com/o2spa | twitter
https://twitter.com/o2spa | pinteres http://www.pinterest.com/o2spa/t |
linkedin https://www.linkedin.com/company/o2-spa?trk=biz-companies-cym |
google+
https://plus.google.com/u/1/b/109281401066564133271/109281401066564133271/posts
