### ISSUE TITLE
Create new outlet Mumbai Novotel in Mumbai

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#54]
Hello Arish,

Create new outlet on mumbai page.Look at the attachment
[O2 Spa new outlet mumbai.docx](https://github.com/adnan1111/o2spaorg/files/251599/O2.Spa.new.outlet.mumbai.docx)
![mumbai novotel khopoli](https://cloud.githubusercontent.com/assets/16165106/15065760/6c5f24a8-1380-11e6-9782-01404f06eefc.png)

Note: Create the outlet in uae.o2spa.org and feedback and enquiry forms
Regards
Prasad

**Comment by arish-ddeveloper** [comment]
done on both India & UAE sites
