### ISSUE TITLE
Create a new outlet Mumbai Transit in Mumbai

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#55]
Hello Arish,

Create a new outlet Mumbai Transit on mumbai page for o2spa.org website. Look at the attachement.

Regards
Prasad
![mumbai-airport-](https://cloud.githubusercontent.com/assets/16165106/15065922/23797552-1382-11e6-9990-8d6fd0ec2fd4.png)
[O2 Spa new mumbai airport outlet.docx](https://github.com/adnan1111/o2spaorg/files/251616/O2.Spa.new.mumbai.airport.outlet.docx)

Regards
Prasad

**Comment by arish-ddeveloper** [comment]
Done on both India & UAE sites
